name: TVB_parallel
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2025.6.15
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.2.1
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libopenblas=0.3.30
  - libsqlite=3.46.0
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libzlib=1.2.13
  - ncurses=6.5
  - openssl=1.1.1w
  - pip=24.3.1
  - python=3.8.0
  - python_abi=3.8
  - readline=8.2
  - setuptools=75.3.0
  - sqlite=3.46.0
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - asciitree==0.3.3
      - attrs==25.3.0
      - cachetools==5.5.2
      - catkin-pkg==1.0.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cloudpickle==3.1.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==5.2.1
      - deprecated==1.2.18
      - diffusers==0.34.0
      - dill==0.4.0
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docutils==0.20.1
      - einops==0.8.1
      - evdev==1.9.2
      - fasteners==0.19
      - filelock==3.16.1
      - fonttools==4.57.0
      - freetype-py==2.5.1
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - gym==0.23.1
      - gym-notices==0.0.8
      - hf-xet==1.1.5
      - hidapi==0.14.0.post4
      - huggingface-hub==0.33.4
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.7
      - llvmlite==0.39.1
      - lxml==6.0.0
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - msgpack==1.1.1
      - ninja==1.11.1.4
      - numba==0.47.0
      - numcodecs==0.12.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.0.3
      - pathtools==0.1.2
      - pillow==10.4.0
      - pkgutil-resolve-name==1.3.10
      - promise==2.3
      - protobuf==3.20.3
      - psutil==5.9.8
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycollada==0.6
      - pygame==2.1.0
      - pyglet==2.1.6
      - pynput==1.8.1
      - pyopengl==3.1.0
      - pyparsing==3.1.4
      - pyrender==0.1.45
      - pysdf==0.1.9
      - python-dateutil==2.9.0.post0
      - python-xlib==0.33
      - pytz==2025.2
      - pyvirtualdisplay==3.0
      - pyyaml==6.0.2
      - ray==2.10.0
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rerun-sdk==0.21.0
      - rl-games==1.6.1
      - rospkg==1.6.0
      - rpds-py==0.20.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - scipy==1.10.1
      - sentry-sdk==2.32.0
      - setproctitle==1.3.6
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - torch==2.2.0
      - torchvision==0.17.0
      - tqdm==4.67.1
      - trimesh==3.23.5
      - triton==2.2.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urdfpy==0.0.22
      - urllib3==2.2.3
      - wandb==0.12.21
      - warp-lang==0.10.1
      - werkzeug==3.0.6
      - wrapt==1.17.2
      - zarr==2.16.1
      - zipp==3.20.2
