
# Task name - used to pick the class to load
task_name: ${task.name}
# experiment name. defaults to name of training config
experiment: ''

# Shape meta for obs keys defined by specific task/config
# this shape_meta is defined in task configs of DP policy
# needs this to override during the runtime
# as the env_runner is instantiated
shape_meta: null

# if set to positive integer, overrides the default number of environments
num_envs: 1
light_factor: 1.0

# set to True for deterministic performance
torch_deterministic: False

## Device config
#  'physx' or 'flex'
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'gpu'
# device for running physics simulation
sim_device: 'cuda:0'
# device to run RL
rl_device: 'cuda:0'
graphics_device_id: 0

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs
num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread

capture_video: False
capture_video_freq: 1464
capture_video_len: 100
force_render: True

# disables rendering
headless: True

# set default task and default training config based on task
defaults:
  - task: TacSLTaskSearchInBox
  - override hydra/job_logging: disabled
  - _self_

# set the directory where the output files get saved
hydra:
  output_subdir: null
  run:
    dir: .